version: '3'
services:
  db:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_DB:postgres
      - POSTGRES_PASSWORD=password
    ports:
      - '<nr-indeksu>:5432'
  frontend:
    image: registry.emontazysta.pl/emontazysta/frontend:latest
    ports:
      - "<nr-indeksu>:80"
  backend: 
    image: registry.emontazysta.pl/emontazysta/warsztaty-docker:master
    ports:
      - "<nr-indeksu>:8080"
    depends_on: 
      - db
     
networks:
  utils_utils:
    external: true
