name: Deploy to Portainer

on:
  push:
    branches:
      - '*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - 
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}    
      - 
        name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile
          tags: ${{ secrets.DOCKER_REGISTRY }}/admin/test-backend:${{ github.ref_name }}
          push: true